# SpringBoot的设置
server:
  port: 18800
spring:
  application:
    name: endpoint-test #为你的应用起个名字，该名字将注册到Eureka注册中心
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true # 404 交给异常处理器处理
  resources:
    add-mappings: false
  datasource:
    poolPreparedStatements: true

token:
  key: YWJj
  expireTime: 3600000 #一小时过期

times: 0,10,20,30,40,50,60

# logback配置
debug: true
logging:
  path: /opt
  file: /opt/stdout.log
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        boot:
          autoconfigure: ERROR
mybatis:
  configuration:
    cache-enabled: true