# 开发环境配置
# 数据源配置，请修改为你项目的实际配置
spring:
  datasource:
    url: jdbc:mysql://api.redmount.cc:3306/test?serverTimezone=GMT%2B8
    username: root
    password: 2wsx@WSX
    driver-class-name: com.mysql.cj.jdbc.Driver
