# 开发环境配置
# 数据源配置，请修改为你项目的实际配置
spring:
  datasource:
    url: jdbc:mysql://192.144.231.168:3306/ssm-with-user?serverTimezone=GMT%2B8
    username: ssm-with-user
    password: 2wsx@WSX
    driver-class-name: com.mysql.cj.jdbc.Driver
upload-file-path: d:\
ali-oss-access-key:
ali-oss-bucket-address:
